name: Build and push Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push base
        run: |
          ./devcontainer/build.py base --push --yes
      
      - name: Build and push conda
        run: |
          ./devcontainer/build.py conda --push --yes
